#pragma once

// Erorr code
#define BKS_ERROR_MSG_NO_FIND_SEQ "{\"CODE\":\"0101\":,\"MSG\":\"BKS_ERROR_MSG_NO_FIND_SEQ\"}"
#define BKS_ERROR_MSG_ALREADY_EXIST_SEQ "{\"CODE\":\"0102\":,\"MSG\":\"BKS_ERROR_MSG_ALREADY_EXIST_SEQ\"}"
#define BKS_ERROR_MSG_NO_PARTICIPANT "{\"CODE\":\"0103\",\"MSG\":\"BKS_ERROR_MSG_NO_PARTICIPANT\"}"
#define BKS_ERROR_MSG_OVER_MAX_PARTICIPANTS "{\"CODE\":\"0104\",\"MSG\":\"BKS_ERROR_MSG_OVER_MAX_PARTICIPANTS\"}"
#define BKS_ERROR_MSG_USER_ALREADY_EXISTS "{\"CODE\":\"0105\",\"MSG\":\"BKS_ERROR_MSG_USER_ALREADY_EXISTS\"}"
#define BKS_ERROR_MSG_ALREADY_END "{\"CODE\":\"0106\",\"MSG\":\"BKS_ERROR_MSG_ALREADY_END\"}"
#define BKS_ERROR_MSG_RANDOM_RANGE "{\"CODE\":\"0107\",\"MSG\":\"BKS_ERROR_MSG_RANDOM_RANGE\"}"
#define BKS_ERROR_TRANSACTION_FAILED "{\"CODE\":\"0108\",\"MSG\":\"BKS_ERROR_TRANSACTION_FAILED\"}"



